name: Deploy theme to Ghost

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "ghost"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          cache: true
          deno-version: latest
      - name: Install Dependencies
        run: deno install
      - name: Build Site
        run: deno x @11ty/eleventy --config ghost.js
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: '_theme'
  deploy:
    environment:
      name: ghost
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v7
      - name: Deploy to Ghost
        uses: TryGhost/action-deploy-theme@v1
        with:
          working-directory: _theme
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
